version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - dependencies
    commit-message:
      prefix: deps
    rebase-strategy: auto
    groups:
      github-actions:
        patterns:
          - "*"
